#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
把  dump.f2fs -i <nid>  的文本解析成
  node_idx → 物理块 → segment/段内偏移
支持：
  · 同时处理多个文件        python3 nid_seg.py nid_85.txt nid_86.txt
  · 自定义 SEG0 / BPS       python3 nid_seg.py -s 0x3000 -b 256 nid_85.txt
"""
import re, argparse

SEG0_DEFAULT = 0x2600      # super-block 里的 segment0_blkaddr
BPS_DEFAULT  = 0x200       # Blocks-Per-Segment (512) for 4 KiB page

# -------------- CLI ----------------
def parse_args():
    p = argparse.ArgumentParser(
        description="Translate dump.f2fs -i output to (segno, offset) list")
    p.add_argument("files", metavar="FILE", nargs="+",
                   help="Text file(s) generated by `dump.f2fs -i <nid>`")
    p.add_argument("-s", "--seg0", type=lambda x: int(x, 0),
                   default=SEG0_DEFAULT,
                   help=f"segment0_blkaddr (hex/dec; default 0x{SEG0_DEFAULT:x})")
    p.add_argument("-b", "--bps", type=int, default=BPS_DEFAULT,
                   help=f"blocks per segment (default {BPS_DEFAULT})")
    return p.parse_args()

# ------------- core ---------------
PAT = re.compile(r'\[\s*(\d+)\]\s*\[0x\s*([0-9a-f]+)\s*:\s*(\d+)\]', re.I)

def nid_seg(path: str, seg0: int, bps: int) -> None:
    with open(path, encoding="utf-8", errors="ignore") as f:
        for m in PAT.finditer(f.read()):
            idx, blk_hex, _ = (int(m.group(1)),
                               int(m.group(2), 16),
                               int(m.group(3)))      # dec 同值，暂不用
            if blk_hex == 0:
                continue            # 洞/未分配
            seg  = (blk_hex - seg0) // bps
            off  = (blk_hex - seg0) %  bps
            print(f"{path}: node_idx={idx:4d} "
                  f"blk=0x{blk_hex:06x} seg={seg:5d} seg_off={off:3d}")

# ------------- entry --------------
def main():
    args = parse_args()
    for fp in args.files:
        nid_seg(fp, args.seg0, args.bps)

if __name__ == "__main__":
    main()
