import fcntl
import os
import time

from .patterns import PatternConfig, iter_expected_chunks
from .sysutil import drop_caches

# F2FS atomic write ioctls (from include/uapi/linux/f2fs.h)
_F2FS_IOCTL_MAGIC = 0xf5
F2FS_IOC_START_ATOMIC_WRITE  = ((_F2FS_IOCTL_MAGIC << 8) | 1)
F2FS_IOC_COMMIT_ATOMIC_WRITE = ((_F2FS_IOCTL_MAGIC << 8) | 2)
F2FS_IOC_ABORT_ATOMIC_WRITE  = ((_F2FS_IOCTL_MAGIC << 8) | 5)
F2FS_IOC_START_ATOMIC_REPLACE = ((_F2FS_IOCTL_MAGIC << 8) | 25)


def atomic_start(fd: int) -> None:
    fcntl.ioctl(fd, F2FS_IOC_START_ATOMIC_WRITE)


def atomic_commit(fd: int) -> None:
    fcntl.ioctl(fd, F2FS_IOC_COMMIT_ATOMIC_WRITE)


def atomic_abort(fd: int) -> None:
    fcntl.ioctl(fd, F2FS_IOC_ABORT_ATOMIC_WRITE)
def ensure_dir(p: str) -> None:
    os.makedirs(p, exist_ok=True)

def open_rw(path: str, create: bool = True) -> int:
    flags = os.O_RDWR | os.O_CLOEXEC
    if create:
        flags |= os.O_CREAT
    return os.open(path, flags, 0o644)

def ensure_file_size(fd: int, size: int) -> None:
    st = os.fstat(fd)
    if st.st_size != size:
        os.ftruncate(fd, size)

def fsync(fd: int) -> None:
    os.fsync(fd)

def pread_scan(fd: int, offset: int, size: int, chunk: int = 256 * 1024, passes: int = 1) -> int:
    """Sequential buffered read via os.pread() (no syscall readahead)."""
    if size <= 0 or passes <= 0:
        return 0
    total = 0
    for _ in range(passes):
        pos = 0
        while pos < size:
            n = min(chunk, size - pos)
            data = os.pread(fd, n, offset + pos)
            if not data:
                break
            total += len(data)
            pos += len(data)
    return total


def read_fd_discard(fd: int, offset: int, size: int, chunk_size: int, passes: int = 1) -> int:
    return pread_scan(fd, offset, size, chunk=chunk_size, passes=passes)


def read_region_discard(path: str, offset: int, size: int, chunk_size: int, passes: int = 1) -> int:
    if size <= 0 or passes <= 0:
        return 0
    fd = os.open(path, os.O_RDONLY)
    try:
        return read_fd_discard(fd, offset, size, chunk_size, passes=passes)
    finally:
        os.close(fd)

def _fill_pattern(buf: bytearray, seed: int, base_off: int) -> None:
    # byte = (seed + abs_off) % 251
    for i in range(len(buf)):
        buf[i] = (seed + base_off + i) % 251

def pwrite_pattern(fd: int, offset: int, size: int, seed: int, chunk: int = 256 * 1024) -> int:
    """Sequential buffered write via os.pwrite()."""
    if size <= 0:
        return 0
    total = 0
    pos = 0
    buf = bytearray(min(chunk, size))
    while pos < size:
        n = min(len(buf), size - pos)
        view = buf if n == len(buf) else buf[:n]
        _fill_pattern(view, seed=seed, base_off=offset + pos)
        wrote = os.pwrite(fd, view, offset + pos)
        if wrote <= 0:
            break
        total += wrote
        pos += wrote
    return total

def sleep_s(seconds: float) -> None:
    if seconds > 0:
        time.sleep(seconds)


def pwrite_pattern_config(fd: int, offset: int, size: int, config: PatternConfig) -> int:
    """Write bytes generated by PatternConfig into [offset, offset+size)."""
    if size <= 0:
        return 0
    total = 0
    for rel_pos, chunk in iter_expected_chunks(offset, size, config):
        wrote = os.pwrite(fd, chunk, offset + rel_pos)
        if wrote != len(chunk):
            raise OSError(f"short pwrite: wrote {wrote} expected {len(chunk)}")
        total += wrote
    return total


def create_and_fill_file(path: str, size: int, config: PatternConfig) -> None:
    """Create a file of `size` bytes filled with `config` pattern, ensuring
    f2fs_inode_may_use_large_folio() returns true so large-folio write paths
    are exercised.

    Protocol:
      1. open(O_CREAT|O_WRONLY|O_TRUNC) + ftruncate(size) + close
         → creates file, triggers inline→block conversion, clears FI_INLINE_DATA.
      2. drop_caches(3) — evicts inode from cache so next open must walk f2fs_iget.
      3. open(O_RDWR) + pwrite + fsync + close
         → f2fs_iget re-evaluates inode_may_use_large_folio (now true),
           mapping_set_folio_min_order is set, writes land on large folios.
    """
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC | os.O_CLOEXEC, 0o644)
    try:
        os.ftruncate(fd, size)
    finally:
        os.close(fd)
    drop_caches(3)
    fd = os.open(path, os.O_RDWR | os.O_CLOEXEC)
    try:
        pwrite_pattern_config(fd, 0, size, config)
        os.fsync(fd)
    finally:
        os.close(fd)
